# Generated by Django 4.2 on 2023-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=122)),
                ('company_desc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='PayMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_id', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=99)),
                ('sender_user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('mode_of_payment', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'payment_sheet',
            },
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'chat_room_detail',
            },
        ),
        migrations.CreateModel(
            name='RoomMaster',
            fields=[
                ('chat_room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_room_name', models.CharField(max_length=200)),
                ('date_creation', models.DateField()),
                ('date_deletion', models.DateField(null=True)),
            ],
            options={
                'db_table': 'chat_room_master',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=122, unique=True)),
                ('pass_word', models.CharField(max_length=16)),
                ('user_full_name', models.CharField(max_length=122)),
                ('company_name', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
    ]
