# Generated by Django 4.2 on 2023-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='pass_word',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='user_full_name',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='username',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='company_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.CharField(default='', max_length=122, unique=True),
        ),
    ]
