# Generated by Django 4.2 on 2023-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_remove_usermaster_pass_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='user_type',
            field=models.CharField(choices=[(0, 'Super Admin'), (1, 'Admin'), (2, 'Staff'), (3, 'Client')], default=3, max_length=2),
        ),
    ]
