# Generated by Django 4.2 on 2023-05-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_usermaster_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='user_full_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
