# Generated by Django 4.2 on 2023-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_usermaster_user_full_name_alter_usermaster_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
