# Generated by Django 4.2 on 2023-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_alter_usermaster_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
