# Generated by Django 4.2 on 2023-05-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_alter_usermaster_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='company_name',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pms.companymaster'),
        ),
    ]
