# Generated by Django 4.2 on 2023-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_remove_usermaster_company_name_usermaster_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='company_id',
            field=models.IntegerField(),
        ),
    ]
