# Generated by Django 4.2 on 2023-05-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_alter_usermaster_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='company_id',
        ),
    ]
