# Generated by Django 4.2 on 2023-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_remove_usermaster_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
