# Generated by Django 4.2 on 2023-05-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_usermaster_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pms.companymaster'),
        ),
    ]
