# Generated by Django 4.2 on 2023-05-30 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_roomdetail_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdetail',
            name='chat_room_id',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.RESTRICT, to='pms.roommaster'),
        ),
    ]
