# Generated by Django 4.2 on 2023-05-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_roomcontent_delete_paymaster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomcontent',
            table='chat_room_content',
        ),
    ]
