# Generated by Django 4.2 on 2023-05-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_alter_roomcontent_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcontent',
            name='chat_room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.roommaster'),
        ),
        migrations.AlterField(
            model_name='roomcontent',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.usermaster'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='chat_room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.roommaster'),
        ),
    ]
