# Generated by Django 4.2 on 2023-05-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_alter_roomcontent_chat_room_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdetail',
            old_name='chat_room_id',
            new_name='chat_r_id',
        ),
    ]
