# Generated by Django 4.2 on 2023-05-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_rename_chat_room_id_roomdetail_chat_r_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='chat_r_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.roommaster'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.usermaster'),
        ),
    ]
