# Generated by Django 4.2 on 2023-05-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0021_rename_chat_r_id_roomdetail_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaster',
            name='chat_room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
