# Generated by Django 4.2 on 2023-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0033_roomdetail_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaster',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
