# Generated by Django 4.2 on 2023-05-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0035_remove_roomdetail_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdetail',
            name='chat_room_id',
        ),
        migrations.DeleteModel(
            name='RoomContent',
        ),
    ]
