# Generated by Django 4.2 on 2023-05-31 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0036_remove_roomdetail_chat_room_id_delete_roomcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetail',
            name='chat_room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.roommaster'),
        ),
    ]
