# Generated by Django 4.2 on 2023-05-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0037_roomdetail_chat_room_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomDetail',
        ),
    ]
