# Generated by Django 4.2 on 2023-05-31 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0038_delete_roomdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.roommaster')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.usermaster')),
            ],
            options={
                'db_table': 'chat_room_detail',
            },
        ),
    ]
