# Generated by Django 4.2 on 2023-06-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0039_roomdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('chat_room_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.roommaster')),
                ('sender_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.usermaster')),
            ],
            options={
                'db_table': 'chat_room_content',
            },
        ),
    ]
