# Generated by Django 4.2 on 2023-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0040_roomcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontent',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
