# Generated by Django 4.2 on 2023-06-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0041_roomcontent_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(default='', max_length=15, unique=True)),
                ('acc_num', models.CharField(default='', max_length=20, unique=True)),
                ('acc_name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('branch_name', models.CharField(default='', max_length=255)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.usermaster')),
            ],
        ),
    ]
