# Generated by Django 4.2 on 2023-06-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0042_paydetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayDetail',
        ),
    ]
