# Generated by Django 4.2 on 2023-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0044_paydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydetail',
            name='qr',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
