# Generated by Django 4.2 on 2023-06-09 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0045_paydetail_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydetail',
            name='c_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='pms.companymaster'),
        ),
        migrations.AlterField(
            model_name='paydetail',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to='pms.usermaster'),
        ),
    ]
