# Generated by Django 4.2 on 2023-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0046_paydetail_c_id_alter_paydetail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
