# Generated by Django 4.2 on 2023-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0047_usermaster_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
