# Generated by Django 4.2 on 2023-06-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0048_alter_usermaster_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pms.companymaster'),
        ),
    ]
