# Generated by Django 4.2 on 2023-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0049_alter_usermaster_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='user_type',
            field=models.CharField(choices=[('0', 'Super Admin'), ('1', 'Admin'), ('2', 'Staff'), ('3', 'Client')], default=3, max_length=2),
        ),
    ]
