# Generated by Django 4.2 on 2023-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0050_alter_usermaster_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='company_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
