# Generated by Django 4.1.7 on 2023-06-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0053_roommaster_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='company_name',
        ),
    ]
