# Generated by Django 4.1.7 on 2023-06-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0054_remove_usermaster_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='token',
        ),
    ]
